# site title
title:yaohwu's personal website

# user name or organization name
user:yaohwu

# issue repository
repository: yaohwu.github.io

# multi-author
authors:yaohwu

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token:e#948fc8fa2d3324d60d4a53e8ba6226daa35362a

# posts per page
perpage:10


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'CREATED_AT'
